### ISSUE TITLE
The instance of the TimeMark interface has been changed in Kotlin 1.7.0-Beta 

### ISSUE THREAD

**Issue by Komdosh** [ReactiveCircus/cache4k#19]
Kotlin has just released 1.7.0-Beta.

But this version raise an exception:

```
java.lang.IncompatibleClassChangeError: Found interface kotlin.time.TimeMark, but class was expected
	at io.github.reactivecircus.cache4k.RealCache.recordWrite(RealCache.kt:236)
	at io.github.reactivecircus.cache4k.RealCache.put(RealCache.kt:136)
	at io.github.reactivecircus.cache4k.RealCache$get$3.invokeSuspend(RealCache.kt:112)
```

It's appear when we use `expire`.

```
Cache.Builder()
    .maximumCacheSize(100)
    .expireAfterWrite(5.minutes)
    .build<String, String>()
```

Kotlin 1.6.20

```
public object Monotonic : TimeSource by MonotonicTimeSource {
    override fun toString(): String = MonotonicTimeSource.toString()
}
```

Kotlin 1.7.0-Beta

```
public object Monotonic : TimeSource {
    override fun markNow(): ValueTimeMark = MonotonicTimeSource.markNow()
    override fun toString(): String = MonotonicTimeSource.toString()

    @ExperimentalTime
    @SinceKotlin("1.7")
    @JvmInline
    public value class ValueTimeMark internal constructor(internal val reading: ValueTimeMarkReading) : TimeMark {
        override fun elapsedNow(): Duration = MonotonicTimeSource.elapsedFrom(this)
        override fun plus(duration: Duration): ValueTimeMark = MonotonicTimeSource.adjustReading(this, duration)
        override fun minus(duration: Duration): ValueTimeMark = MonotonicTimeSource.adjustReading(this, -duration)
        override fun hasPassedNow(): Boolean = !elapsedNow().isNegative()
        override fun hasNotPassedNow(): Boolean = elapsedNow().isNegative()
    }
}
```

**Comment by Milchschlumpf** [comment]
Any update on this? Since Kotlin 1.7.0 is released, this blocks the upgrade to Kotlin 1.7.0

**Comment by ychescale9** [comment]
Can you try the latest release? This shouldn't be an issue anymore as the binary incompatible time API has been removed from our public API.

**Comment by Milchschlumpf** [comment]
When I use the current 0.7.0-SNAPSHOT version in my project, the issue is gone.

**Comment by ychescale9** [comment]
Just released 0.7.0 😄
